#!/bin/sh
#
# ** The MIT License **
#
# Copyright (c) 2013 Andrei Gherzan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

#
# A tiny script which sends a notify message to system when new message arrives in centerim
#
# Home: https://github.com/agherzan/centsent
#
# Author: Andrei Gherzan <andrei@gherzan.ro>
#

CENTERIM=centerim5

ACTIVEPID=`xdotool getwindowpid $(xdotool getwindowfocus)`
CENPID=`pidof -s $CENTERIM`

# Start with centerim pid and go to all parents until we find ACTIVEPID
# If we find ACTIVEPID exit script
current=$CENPID
while [ "$current" != "1" ]; do
    # No spaces please
    parent=`ps -p $current -o ppid= | sed 's/ //g'`
    if [ "$parent" == "$ACTIVEPID" ]; then
        exit 0
    fi
    current=$parent
done

# If we get here then we didn't find ACTIVEPID in patrent tree
notify-send -u low -t 100 "Centerim message from: $EVENT_REMOTE_USER" "Message: $EVENT_MESSAGE \n $CURPID"
